PRODUIT = (Id_PRODUIT COUNTER, type_PRODUIT VARCHAR(50), genre_PRODUIT VARCHAR(1), prix_PRODUIT CURRENCY, char_PRODUIT VARCHAR(1));
VETEMENT = (taille_VETEMENT VARCHAR(3), #Id_PRODUIT);
CHAUSSURE = (pointure_CHAUSSURE INT, #Id_PRODUIT);
CLIENT = (Id_CLIENT COUNTER, prenom_CLIENT VARCHAR(20), nom_CLIENT VARCHAR(20), date_de_naissance_CLIENT DATE, adresse_CLIENT VARCHAR(50), code_postal_CLIENT VARCHAR(10), ville_CLIENT VARCHAR(20), telephone_CLIENT VARCHAR(15), mail_CLIENT VARCHAR(40));
COMMANDE = (Id_COMMANDE COUNTER, total_COMMANDE CURRENCY, #Id_CLIENT);
COMPOSER = (#Id_PRODUIT, #Id_COMMANDE, quantité INT);
AIMER = (#Id_PRODUIT, #Id_CLIENT);
